events { worker_connections 1024; }

http {
    default_type  application/octet-stream;

    # Gzip compression
    gzip on;
    gzip_types text/html text/css application/javascript application/json;

    # Cache static files
    server {
        listen 80;

        # Static files — serve trực tiếp, không qua app server
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;

            # Cache HTML 5 phút, assets 1 năm
            location ~* \.(js|css|png|jpg|ico)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
        }

        # API calls — proxy đến Spring Boot
        location /api/ {
            # proxy_pass http://172.17.0.1:8080;
            proxy_pass http://172.21.192.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Rate limiting — tránh abuse
            limit_req zone=api_limit burst=20 nodelay;
        }
    }

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=30r/s;
}